### ISSUE TITLE
Tasks tracking

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-deployment#19]
Quick summary of things left to do:

- [x] Fix s3 credentials handling (https://github.com/developmentseed/ram-deployment/pull/18#issuecomment-446180962)
- [x] Investigate bucket creation by cloudformation (The bucket needs to be created manually. See if it is possible to have this done automatically. Each instance should also have a storage bucket different from the one where the config is uploaded to.)
- [x] Investigate what's the most appropriate machine size for each of the containers.
- [x] Review docs in light of new variables and process changes
- [x] Make `yarn setup` more explicit when destroying the database.
- [x] review the open ports (do we need 5432?)
